---

version: "3"
services:
  db-nestjs-coffee:
    image:  postgres
    restart: always 
    ports:
      - "5445:5432"
    environment:
      POSTGRES_PASSWORD: pass123
  
  db-test-nestjs-coffee:
    image: postgres
    restart: always
    ports:
      - "5444:5432"
    environment: 
      POSTGRES_PASSWORD: pass123